# ================================================================================================
# HVI 2.0 | Long-term annual heat-burden forecast frontend exports
# Builds annual community-endpoint model matrices and 5/10/20-year forecast artifacts.
#
# This is an annual planning layer, not a replacement for the daily operational HVI. Forecasts are
# generated by shifting a baseline year of daily temperatures, scoring the existing endpoint HVI
# models, and aggregating heat-attributable excess burden to community-area-year outputs.
# ================================================================================================

suppressPackageStartupMessages({
  library(tidyverse)
  library(janitor)
  library(lubridate)
  library(readr)
  library(stringr)
})

source(file.path(if (dir.exists("code")) "code" else ".", "00_config.R"))
hvi_source("09_utils_hvi.R")

if (!requireNamespace("mgcv", quietly = TRUE)) {
  stop("The mgcv package is required to score saved endpoint models.")
}

# -----------------------------
# Config
# -----------------------------
project_dir <- HVI_PATHS$private
out_dir <- ensure_output_dir(project_dir, "09_model_outputs")
frontend_dir <- file.path(out_dir, "frontend_exports")
hvi_dir_create(frontend_dir)

horizons_years <- as.integer(strsplit(hvi_env("HVI_FORECAST_HORIZONS_YEARS", "5,10,20"), ",")[[1]])
horizons_years <- horizons_years[is.finite(horizons_years) & horizons_years > 0]
if (length(horizons_years) == 0) horizons_years <- c(5L, 10L, 20L)

baseline_year_override <- suppressWarnings(as.integer(hvi_env("HVI_FORECAST_BASELINE_YEAR", NA_character_)))
scenario_delta_c_values <- suppressWarnings(as.numeric(strsplit(hvi_env("HVI_FORECAST_WARMING_DELTAS_C", "0.5,1,2,3"), ",")[[1]]))
scenario_delta_c_values <- scenario_delta_c_values[is.finite(scenario_delta_c_values) & scenario_delta_c_values > 0]
daily_event_rate_cap <- suppressWarnings(as.numeric(hvi_env("HVI_FORECAST_DAILY_EVENT_RATE_CAP", "0.02")))
if (!is.finite(daily_event_rate_cap) || daily_event_rate_cap <= 0) daily_event_rate_cap <- 0.02
empirical_daily_cap_multiplier <- suppressWarnings(as.numeric(hvi_env("HVI_FORECAST_EMPIRICAL_DAILY_CAP_MULTIPLIER", "3")))
if (!is.finite(empirical_daily_cap_multiplier) || empirical_daily_cap_multiplier <= 0) empirical_daily_cap_multiplier <- 3

model_matrix_candidates <- c(
  file.path(HVI_PATHS$private, "hvi_model_matrix_2019_2022.csv"),
  file.path(HVI_PATHS$repo, "hvi_model_matrix_2019_2022.csv")
)
endpoint_meta_candidates <- c(
  file.path(HVI_PATHS$private, "hvi_endpoint_metadata.csv"),
  file.path(HVI_PATHS$private_outputs$model_outputs, "hvi_endpoint_metadata.csv")
)
endpoint_weight_candidates <- c(
  file.path(HVI_PATHS$private_outputs$model_outputs, "09b_endpoint_weights.csv"),
  file.path(HVI_PATHS$repo, "code", "09_model_outputs", "09b_endpoint_weights.csv")
)
endpoint_model_candidates <- c(
  file.path(HVI_PATHS$private_outputs$model_outputs, "09a_endpoint_models.rds"),
  file.path(HVI_PATHS$repo, "code", "09_model_outputs", "09a_endpoint_models.rds")
)
climate_candidates <- c(
  HVI_PATHS$raw$climate_full,
  HVI_PATHS$raw$climate_hist,
  file.path(HVI_PATHS$private, "Climate", "CA_temps_rh_90-24.csv"),
  file.path(HVI_PATHS$private, "Climate", "CA_temps_rh_90-23.csv")
)

pick_existing <- function(paths, label) {
  hit <- paths[file.exists(paths)][1]
  if (length(hit) == 0 || is.na(hit)) stop("Missing required ", label, ". Checked: ", paste(paths, collapse = "; "))
  hit
}

clean_community <- function(x) {
  x %>%
    as.character() %>%
    str_to_upper() %>%
    str_replace_all("&", "AND") %>%
    str_replace_all("[[:punct:]]", " ") %>%
    str_squish() %>%
    str_replace("^O HARE$", "OHARE")
}

c_to_f <- function(x) (x * 9 / 5) + 32

safe_rate <- function(count, pop) {
  if_else(!is.na(pop) & pop > 0, 100000 * count / pop, NA_real_)
}

format_delta_id <- function(x) {
  str_replace_all(sprintf("%.2f", x) %>% str_replace("0+$", "") %>% str_replace("\\.$", ""), "\\.", "p")
}

lagged_sum <- function(x, max_lag) {
  x <- replace_na(as.numeric(x), 0)
  k <- max(0L, as.integer(max_lag))
  vapply(seq_along(x), function(i) sum(x[max(1L, i - k):i], na.rm = TRUE), numeric(1))
}

harmonize_for_fit <- function(dat, fit) {
  dat <- dat %>%
    mutate(
      community = as.character(community),
      date = as.Date(date),
      doy = as.integer(doy)
    )

  if (!is.null(fit$xlevels) && "dow" %in% names(fit$xlevels)) {
    dat <- dat %>% mutate(dow = factor(as.character(dow), levels = fit$xlevels[["dow"]]))
  } else {
    dat <- dat %>% mutate(dow = factor(as.character(dow)))
  }

  if (!is.null(fit$xlevels) && "year" %in% names(fit$xlevels)) {
    dat <- dat %>% mutate(year = factor(as.character(year), levels = fit$xlevels[["year"]]))
  } else {
    dat <- dat %>% mutate(year = factor(as.character(year)))
  }

  dat
}

score_heat_excess <- function(fit, dat, all_model_vars) {
  vars_needed <- intersect(all_model_vars, names(dat))
  dat <- dat %>%
    tidyr::drop_na(dplyr::any_of(vars_needed)) %>%
    as.data.frame()

  if (nrow(dat) == 0) {
    return(tibble(
      community = character(), date = as.Date(character()),
      predicted_count = numeric(), reference_count = numeric(),
      excess_events_signed = numeric(), excess_events_heat = numeric()
    ))
  }

  ref_dat <- dat
  ref_dat$heat_dose <- 0

  response_from_link <- function(newdata) {
    eta <- as.numeric(mgcv::predict.gam(fit, newdata = newdata, type = "link"))
    population_cap <- pmax(as.numeric(newdata$pop_offset) * daily_event_rate_cap, 1, na.rm = TRUE)
    empirical_cap <- rep(NA_real_, nrow(newdata))
    if ("outcome" %in% names(newdata)) {
      empirical_cap <- ave(
        suppressWarnings(as.numeric(newdata$outcome)),
        newdata$community,
        FUN = function(z) {
          z <- z[is.finite(z)]
          if (length(z) == 0) return(NA_real_)
          max(max(z, na.rm = TRUE) * empirical_daily_cap_multiplier, 1)
        }
      )
    }
    cap <- if_else(is.finite(empirical_cap), pmin(empirical_cap, population_cap), population_cap)
    link_cap <- log(cap)
    capped <- is.finite(eta) & eta > link_cap
    positive_inf <- is.infinite(eta) & eta > 0
    eta <- pmin(eta, link_cap)
    eta[positive_inf] <- link_cap[positive_inf]
    count <- exp(eta)
    count[is.infinite(count) & count > 0] <- cap[is.infinite(count) & count > 0]
    count[is.nan(count)] <- NA_real_

    list(count = count, capped = capped | positive_inf)
  }

  predicted <- response_from_link(dat)
  reference <- response_from_link(ref_dat)
  predicted_count <- predicted$count
  reference_count <- reference$count
  excess_events_signed <- predicted_count - reference_count

  tibble(
    community = dat$community,
    date = as.Date(dat$date),
    predicted_count = predicted_count,
    reference_count = reference_count,
    excess_events_signed = excess_events_signed,
    excess_events_heat = pmax(excess_events_signed, 0),
    prediction_capped = predicted$capped | reference$capped
  )
}

# -----------------------------
# Load inputs
# -----------------------------
model_matrix_path <- pick_existing(model_matrix_candidates, "hvi_model_matrix_2019_2022.csv")
endpoint_meta_path <- pick_existing(endpoint_meta_candidates, "hvi_endpoint_metadata.csv")
endpoint_weight_path <- pick_existing(endpoint_weight_candidates, "09b_endpoint_weights.csv")
endpoint_model_path <- pick_existing(endpoint_model_candidates, "09a_endpoint_models.rds")
climate_path <- pick_existing(climate_candidates, "long climate panel")

hvi_model_matrix <- read_csv(model_matrix_path, show_col_types = FALSE) %>%
  clean_names() %>%
  mutate(
    community = clean_community(community),
    date = as.Date(date),
    year = as.integer(year),
    doy = as.integer(doy),
    dow = factor(as.character(dow), levels = c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"))
  )

if (all(is.na(hvi_model_matrix$dow)) && "date" %in% names(hvi_model_matrix)) {
  hvi_model_matrix <- hvi_model_matrix %>%
    mutate(
      dow = factor(
        c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")[lubridate::wday(date)],
        levels = c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")
      )
    )
}

hvi_endpoint_metadata <- read_csv(endpoint_meta_path, show_col_types = FALSE) %>%
  clean_names() %>%
  mutate(endpoint_key = as.character(endpoint_key))

endpoint_weights <- read_csv(endpoint_weight_path, show_col_types = FALSE) %>%
  clean_names() %>%
  mutate(endpoint_key = as.character(endpoint_key))

endpoint_models <- readRDS(endpoint_model_path)

climate_long <- read_csv(climate_path, show_col_types = FALSE) %>% clean_names()

climate_date_col <- c("event_date", "date")[c("event_date", "date") %in% names(climate_long)][1]
climate_temp_col <- c("tmax", "temp_max", "daily_max_temp", "temperature_c", "temperature")[c("tmax", "temp_max", "daily_max_temp", "temperature_c", "temperature") %in% names(climate_long)][1]
if (is.na(climate_date_col) || is.na(climate_temp_col)) {
  stop("Climate panel must include a date column and a daily maximum temperature column.")
}

climate_annual <- climate_long %>%
  transmute(
    date = as.Date(.data[[climate_date_col]]),
    year = year(date),
    tmax = suppressWarnings(as.numeric(.data[[climate_temp_col]]))
  ) %>%
  filter(!is.na(year), is.finite(tmax)) %>%
  group_by(year) %>%
  summarise(citywide_annual_mean_temp_c = mean(tmax, na.rm = TRUE), .groups = "drop")

trend_override <- suppressWarnings(as.numeric(hvi_env("HVI_FORECAST_TEMP_TREND_C_PER_YEAR", NA_character_)))
if (is.finite(trend_override)) {
  temp_trend_c_per_year <- trend_override
  temp_trend_source <- "HVI_FORECAST_TEMP_TREND_C_PER_YEAR"
} else {
  trend_fit <- lm(citywide_annual_mean_temp_c ~ year, data = climate_annual)
  temp_trend_c_per_year <- unname(coef(trend_fit)[["year"]])
  temp_trend_source <- basename(climate_path)
}

if (!is.finite(temp_trend_c_per_year)) {
  stop("Could not estimate or read a finite annual temperature trend.")
}

temp_col <- c("tmax", "temp_max", "daily_max_temp", "temperature_c", "temperature")
temp_col <- temp_col[temp_col %in% names(hvi_model_matrix)][1]
if (is.na(temp_col)) stop("Could not find a temperature column in hvi_model_matrix.")

available_years <- sort(unique(hvi_model_matrix$year[is.finite(hvi_model_matrix$year)]))
baseline_year <- if (is.finite(baseline_year_override) && baseline_year_override %in% available_years) {
  baseline_year_override
} else {
  max(available_years, na.rm = TRUE)
}

endpoint_keys <- intersect(names(endpoint_models), hvi_endpoint_metadata$endpoint_key)
endpoint_keys <- endpoint_keys[hvi_endpoint_metadata$panel_outcome_col[match(endpoint_keys, hvi_endpoint_metadata$endpoint_key)] %in% names(hvi_model_matrix)]

# -----------------------------
# Annual historical QA matrix
# -----------------------------
annual_base <- hvi_model_matrix %>%
  group_by(community, year) %>%
  summarise(
    days_observed = n_distinct(date),
    annual_mean_temp_c = mean(.data[[temp_col]], na.rm = TRUE),
    annual_max_temp_c = max(.data[[temp_col]], na.rm = TRUE),
    annual_mean_humidity = if ("humidity" %in% names(hvi_model_matrix)) mean(humidity, na.rm = TRUE) else NA_real_,
    population = if ("pop_offset" %in% names(hvi_model_matrix)) mean(pop_offset, na.rm = TRUE) else NA_real_,
    tree_canopy_pct = if ("tree_canopy_pct" %in% names(hvi_model_matrix)) mean(tree_canopy_pct, na.rm = TRUE) else NA_real_,
    tree_canopy_fraction = if ("tree_canopy_fraction" %in% names(hvi_model_matrix)) mean(tree_canopy_fraction, na.rm = TRUE) else NA_real_,
    ndvi = if ("ndvi" %in% names(hvi_model_matrix)) mean(ndvi, na.rm = TRUE) else NA_real_,
    ac_prob = if ("ac_prob" %in% names(hvi_model_matrix)) mean(ac_prob, na.rm = TRUE) else NA_real_,
    .groups = "drop"
  ) %>%
  mutate(
    annual_mean_temp_f = c_to_f(annual_mean_temp_c),
    annual_max_temp_f = c_to_f(annual_max_temp_c)
  )

outcome_annual <- map_dfr(seq_len(nrow(hvi_endpoint_metadata)), function(i) {
  ep <- hvi_endpoint_metadata$endpoint_key[i]
  outcome_col <- hvi_endpoint_metadata$panel_outcome_col[i]
  if (!ep %in% endpoint_keys || !outcome_col %in% names(hvi_model_matrix)) return(tibble())

  mrt_val <- suppressWarnings(as.numeric(hvi_endpoint_metadata$mrt[i]))
  heat_dose_col <- get_heat_var(ep, hvi_model_matrix)

  hvi_model_matrix %>%
    group_by(community, year) %>%
    summarise(
      observed_count = sum(.data[[outcome_col]], na.rm = TRUE),
      annual_heat_days = if (is.finite(mrt_val)) sum(.data[[temp_col]] > mrt_val, na.rm = TRUE) else NA_real_,
      annual_heat_dose = if (!is.na(heat_dose_col)) {
        sum(.data[[heat_dose_col]], na.rm = TRUE)
      } else if (is.finite(mrt_val)) {
        sum(pmax(.data[[temp_col]] - mrt_val, 0), na.rm = TRUE)
      } else {
        NA_real_
      },
      .groups = "drop"
    ) %>%
    mutate(endpoint_key = ep)
})

frontend_forecast_annual_model_matrix <- outcome_annual %>%
  left_join(annual_base, by = c("community", "year")) %>%
  left_join(
    hvi_endpoint_metadata %>%
      select(endpoint_key, outcome_label, source, domain, mrt, max_lag),
    by = "endpoint_key"
  ) %>%
  mutate(
    event_family = source,
    observed_rate_per_100k = safe_rate(observed_count, population)
  ) %>%
  select(
    community, year, endpoint_key, event_family, outcome_label, domain,
    days_observed, annual_mean_temp_c, annual_mean_temp_f,
    annual_max_temp_c, annual_max_temp_f, annual_mean_humidity,
    annual_heat_days, annual_heat_dose,
    population, observed_count, observed_rate_per_100k,
    tree_canopy_pct, tree_canopy_fraction, ndvi, ac_prob,
    mrt, max_lag
  ) %>%
  arrange(endpoint_key, community, year)

# -----------------------------
# Forecast scenarios scored through daily endpoint models
# -----------------------------
baseline_daily <- hvi_model_matrix %>%
  filter(year == baseline_year) %>%
  mutate(model_year = as.character(year))

trend_scenarios <- tibble(
  forecast_basis = "trend_horizon",
  horizon_years = horizons_years,
  forecast_year = baseline_year + horizons_years,
  temperature_delta_c = temp_trend_c_per_year * horizons_years,
  scenario_label = paste0(horizons_years, "y trend")
)

fixed_warming_scenarios <- tibble(
  forecast_basis = "fixed_warming_delta",
  horizon_years = NA_integer_,
  forecast_year = NA_integer_,
  temperature_delta_c = scenario_delta_c_values,
  scenario_label = paste0("+", scenario_delta_c_values, " C")
)

forecast_scenarios <- bind_rows(trend_scenarios, fixed_warming_scenarios) %>%
  mutate(
    scenario_id = if_else(
      forecast_basis == "trend_horizon",
      paste0("trend_", horizon_years, "y"),
      paste0("warming_", format_delta_id(temperature_delta_c), "c")
    ),
    temperature_delta_f = temperature_delta_c * 9 / 5
  )

endpoint_forecast_list <- list()

for (ep_key in endpoint_keys) {
  message("Forecasting endpoint: ", ep_key)

  fit <- endpoint_models[[ep_key]]
  meta_row <- hvi_endpoint_metadata %>% filter(endpoint_key == ep_key)
  if (nrow(meta_row) == 0) next

  outcome_var <- meta_row$panel_outcome_col[1]
  heat_var <- get_heat_var(ep_key, baseline_daily)
  if (length(heat_var) == 0 || is.na(heat_var)) next

  all_model_vars <- all.vars(formula(fit))
  z_vars_use <- all_model_vars[stringr::str_detect(all_model_vars, "^z_")]
  model_adjustment_vars <- intersect(
    setdiff(all_model_vars, c("outcome", "heat_dose", "pop_offset", "doy", "dow", "year", z_vars_use)),
    names(baseline_daily)
  )

  base_score_df <- baseline_daily %>%
    select(
      community, date, model_year, doy, dow, pop_offset, all_of(temp_col),
      any_of(outcome_var), all_of(heat_var), any_of(z_vars_use), any_of(model_adjustment_vars)
    ) %>%
    rename(
      year = model_year,
      outcome = any_of(outcome_var),
      heat_dose = all_of(heat_var),
      baseline_temp_c = all_of(temp_col)
    ) %>%
    tidyr::drop_na(heat_dose, doy, dow, year)

  base_score_df <- harmonize_for_fit(base_score_df, fit)
  baseline_daily_excess <- score_heat_excess(fit, base_score_df, all_model_vars) %>%
    rename(
      baseline_predicted_count = predicted_count,
      baseline_reference_count = reference_count,
      baseline_excess_signed = excess_events_signed,
      baseline_excess_heat = excess_events_heat,
      baseline_prediction_capped = prediction_capped
    )

  scenario_rows <- map_dfr(seq_len(nrow(forecast_scenarios)), function(i) {
    sc <- forecast_scenarios[i, ]
    mrt_val <- suppressWarnings(as.numeric(meta_row$mrt[1]))
    max_lag_val <- suppressWarnings(as.integer(meta_row$max_lag[1]))
    if (!is.finite(max_lag_val)) max_lag_val <- 0L

    forecast_df <- base_score_df %>%
      mutate(
        scenario_id = sc$scenario_id,
        forecast_basis = sc$forecast_basis,
        scenario_label = sc$scenario_label,
        horizon_years = sc$horizon_years,
        baseline_year = baseline_year,
        forecast_year = sc$forecast_year,
        temperature_delta_c = sc$temperature_delta_c,
        temperature_delta_f = sc$temperature_delta_f,
        forecast_temp_c = baseline_temp_c + sc$temperature_delta_c
      ) %>%
      group_by(community) %>%
      arrange(date, .by_group = TRUE) %>%
      mutate(
        forecast_temp_excess = pmax(forecast_temp_c - mrt_val, 0),
        heat_dose = lagged_sum(forecast_temp_excess, max_lag_val)
      ) %>%
      ungroup()

    forecast_daily_excess <- score_heat_excess(fit, forecast_df, all_model_vars) %>%
      rename(
        forecast_predicted_count = predicted_count,
        forecast_reference_count = reference_count,
        forecast_excess_signed = excess_events_signed,
        forecast_excess_heat = excess_events_heat,
        forecast_prediction_capped = prediction_capped
      )

    forecast_df %>%
      select(
        community, date, scenario_id, forecast_basis, scenario_label,
        horizon_years, baseline_year, forecast_year,
        temperature_delta_c, temperature_delta_f,
        baseline_temp_c, forecast_temp_c, pop_offset
      ) %>%
      left_join(baseline_daily_excess, by = c("community", "date")) %>%
      left_join(forecast_daily_excess, by = c("community", "date")) %>%
      group_by(community, scenario_id, forecast_basis, scenario_label, horizon_years, baseline_year, forecast_year) %>%
      summarise(
        endpoint_key = ep_key,
        event_family = meta_row$source[1],
        outcome_label = meta_row$outcome_label[1],
        domain = meta_row$domain[1],
        annual_mean_temp_c = mean(forecast_temp_c, na.rm = TRUE),
        annual_mean_temp_f = c_to_f(annual_mean_temp_c),
        annual_max_temp_c = max(forecast_temp_c, na.rm = TRUE),
        annual_max_temp_f = c_to_f(annual_max_temp_c),
        temperature_delta_c = first(temperature_delta_c),
        temperature_delta_f = first(temperature_delta_f),
        temp_trend_c_per_year = temp_trend_c_per_year,
        population = mean(pop_offset, na.rm = TRUE),
        baseline_predicted_count = sum(baseline_predicted_count, na.rm = TRUE),
        baseline_reference_count = sum(baseline_reference_count, na.rm = TRUE),
        baseline_excess_signed = sum(baseline_excess_signed, na.rm = TRUE),
        baseline_excess_heat = sum(baseline_excess_heat, na.rm = TRUE),
        forecast_predicted_count = sum(forecast_predicted_count, na.rm = TRUE),
        forecast_reference_count = sum(forecast_reference_count, na.rm = TRUE),
        forecast_excess_signed = sum(forecast_excess_signed, na.rm = TRUE),
        forecast_excess_heat = sum(forecast_excess_heat, na.rm = TRUE),
        forecast_excess_signed_change = forecast_excess_signed - baseline_excess_signed,
        additional_heat_burden = pmax(forecast_excess_heat - baseline_excess_heat, 0),
        baseline_heat_rate_per_100k = safe_rate(baseline_excess_heat, population),
        forecast_heat_rate_per_100k = safe_rate(forecast_excess_heat, population),
        additional_heat_rate_per_100k = safe_rate(additional_heat_burden, population),
        baseline_annual_heat_days = sum(baseline_temp_c > mrt_val, na.rm = TRUE),
        forecast_annual_heat_days = sum(forecast_temp_c > mrt_val, na.rm = TRUE),
        baseline_annual_heat_dose = sum(pmax(baseline_temp_c - mrt_val, 0), na.rm = TRUE),
        forecast_annual_heat_dose = sum(pmax(forecast_temp_c - mrt_val, 0), na.rm = TRUE),
        model_type = "daily_endpoint_hvi_shifted_temperature",
        capped_prediction_days = sum(baseline_prediction_capped | forecast_prediction_capped, na.rm = TRUE),
        nonfinite_prediction_days = sum(
          !is.finite(baseline_predicted_count) | !is.finite(baseline_reference_count) |
            !is.finite(forecast_predicted_count) | !is.finite(forecast_reference_count),
          na.rm = TRUE
        ),
        model_status = case_when(
          nonfinite_prediction_days > 0 ~ "nonfinite_removed",
          capped_prediction_days > 0 ~ "prediction_capped",
          TRUE ~ "ok"
        ),
        .groups = "drop"
      )
  })

  endpoint_forecast_list[[ep_key]] <- scenario_rows
}

forecast_endpoint <- bind_rows(endpoint_forecast_list) %>%
  arrange(forecast_basis, horizon_years, temperature_delta_c, endpoint_key, community)

weight_cols <- endpoint_weights %>%
  select(any_of(c("endpoint_key", "endpoint_weight", "source_weight", "performance_weight"))) %>%
  mutate(endpoint_weight = coalesce(endpoint_weight, 1))

forecast_endpoint_weighted <- forecast_endpoint %>%
  left_join(weight_cols, by = "endpoint_key") %>%
  mutate(endpoint_weight = coalesce(endpoint_weight, 1))

dominant_forecast_endpoint <- forecast_endpoint_weighted %>%
  group_by(community, scenario_id, forecast_basis, scenario_label, horizon_years, baseline_year, forecast_year) %>%
  slice_max(order_by = additional_heat_burden, n = 1, with_ties = FALSE) %>%
  ungroup() %>%
  transmute(
    community, scenario_id, forecast_basis, scenario_label, horizon_years, baseline_year, forecast_year,
    dominant_endpoint = endpoint_key,
    dominant_endpoint_label = outcome_label,
    dominant_endpoint_source = event_family,
    dominant_endpoint_additional_heat_burden = additional_heat_burden
  )

frontend_long_term_forecast_overall <- forecast_endpoint_weighted %>%
  group_by(community, scenario_id, forecast_basis, scenario_label, horizon_years, baseline_year, forecast_year) %>%
  summarise(
    annual_mean_temp_c = first(annual_mean_temp_c),
    annual_mean_temp_f = first(annual_mean_temp_f),
    temperature_delta_c = first(temperature_delta_c),
    temperature_delta_f = first(temperature_delta_f),
    population = first(population),
    total_baseline_excess_heat = sum(baseline_excess_heat, na.rm = TRUE),
    total_forecast_excess_heat = sum(forecast_excess_heat, na.rm = TRUE),
    total_additional_heat_burden = sum(additional_heat_burden, na.rm = TRUE),
    total_forecast_excess_signed_change = sum(forecast_excess_signed_change, na.rm = TRUE),
    overall_weighted_additional_heat_burden = weighted.mean(additional_heat_burden, w = endpoint_weight, na.rm = TRUE),
    n_endpoints = n_distinct(endpoint_key),
    .groups = "drop"
  ) %>%
  group_by(scenario_id) %>%
  mutate(
    forecast_risk_0_100 = rescale_positive_0_100(overall_weighted_additional_heat_burden),
    forecast_tier = cut(
      forecast_risk_0_100,
      breaks = c(-Inf, 25, 50, 75, Inf),
      labels = c("Low", "Moderate", "High", "Very High"),
      include.lowest = TRUE,
      right = TRUE
    )
  ) %>%
  ungroup() %>%
  left_join(
    dominant_forecast_endpoint,
    by = c("community", "scenario_id", "forecast_basis", "scenario_label", "horizon_years", "baseline_year", "forecast_year")
  ) %>%
  arrange(forecast_basis, horizon_years, temperature_delta_c, desc(forecast_risk_0_100), community)

frontend_long_term_forecast_metadata <- tibble(
  generated_at = format(Sys.time(), "%Y-%m-%dT%H:%M:%S%z"),
  baseline_year = baseline_year,
  horizons_years = paste(horizons_years, collapse = "|"),
  fixed_warming_deltas_c = paste(scenario_delta_c_values, collapse = "|"),
  climate_trend_source = temp_trend_source,
  climate_trend_start_year = min(climate_annual$year, na.rm = TRUE),
  climate_trend_end_year = max(climate_annual$year, na.rm = TRUE),
  temp_trend_c_per_year = temp_trend_c_per_year,
  temp_trend_f_per_year = temp_trend_c_per_year * 9 / 5,
  forecast_method = "shifted_daily_temperature_existing_hvi_models",
  model_note = paste(
    "Forecasts shift baseline-year daily temperatures, recompute endpoint-specific heat dose,",
    "score the existing endpoint HVI models, and aggregate annual heat-attributable excess.",
    "Public burden fields report nonnegative additional heat-attributable burden; signed changes are retained for QA."
  )
)

# -----------------------------
# Export
# -----------------------------
write_csv(frontend_forecast_annual_model_matrix, file.path(frontend_dir, "frontend_forecast_annual_model_matrix.csv"))
write_csv(forecast_endpoint, file.path(frontend_dir, "frontend_long_term_forecast_endpoint.csv"))
write_csv(frontend_long_term_forecast_overall, file.path(frontend_dir, "frontend_long_term_forecast_overall.csv"))
write_csv(frontend_long_term_forecast_metadata, file.path(frontend_dir, "frontend_long_term_forecast_metadata.csv"))

assign("frontend_forecast_annual_model_matrix", frontend_forecast_annual_model_matrix, envir = .GlobalEnv)
assign("frontend_long_term_forecast_endpoint", forecast_endpoint, envir = .GlobalEnv)
assign("frontend_long_term_forecast_overall", frontend_long_term_forecast_overall, envir = .GlobalEnv)
assign("frontend_long_term_forecast_metadata", frontend_long_term_forecast_metadata, envir = .GlobalEnv)

message("13 complete. Long-term heat-burden forecast frontend exports written to: ", frontend_dir)
